### PR TITLE
Fix bug in plot, loglog: let within if was capturing rest of closure

### PR DESCRIPTION
**Pull request by mars0i**
plot, loglog: added parentheses around let in 'if marker'

In the closure definition in `plot`, because the `let` in scope of `if marker ...` wasn't wrapped in parentheses, the `let` extended to the rest of the closure, and nothing else got executed if the `if` test failed. It's also clear from the indentation that this isn't what was intended.  Plot settings weren't getting rrestored to their previous values at the end of the closure, which caused some of the settings to carry over to the next closure when it was executed.

This fixes issue #113.  I don't know why the PR includes some old commits from my previous PR.  Let me know if I need to redo this one.

It seems clear that the same problem exists in loglog, so I fixed that. (EDIT: At first I couldn't run `loglog` just to test that I hadn't broken something, but now I figured out how to do that.)

(I haven't noticed other functions in owl_plot.ml that have this problem.  I searched through all 'if' expressions that use 'marker'.  Difficult to search for an if followed by a let on the next line.)

(This is the `loglog` error:
```ocaml
# let xs = M.sequential 1 10;;
val xs : M.mat =
   C0 C1 C2 C3 C4 C5 C6 C7 C8 C9
R0  0  1  2  3  4  5  6  7  8  9

# let h = Owl.Plot.create "foo.pdf" in Owl.Plot.(loglog ~h xs ; output h);;
Exception: Gsl__Error.Gsl_exn (Gsl__Error.EDOM, "domain error").
Raised by primitive operation at unknown location
Called from file "src/owl/owl_maths.ml", line 89, characters 14-21
Called from file "array.ml", line 91, characters 21-40
Called from file "src/owl/owl_plot.ml", line 1236, characters 41-68
Called from file "//toplevel//", line 1, characters 47-59
Called from file "toplevel/toploop.ml", line 180, characters 17-56
```
I'll try to figure out whether I'm doing something wrong and file an issue if need be.)

### CODE REVIEW

**Comment by jzstark** [comment]
@mars0i Thank you so much for finding out and fixing this problem! I wrote the `loglog` function based on `plot` and I think that's why they share the same problem.

**Comment by ryanrhymes** [comment]
This is definitely a bug, many thanks for fixing it @mars0i 

For the second issue, I think the reason is the `0` in `xs`, which `loglog` will call `Maths.log 0` which will throw that exception.

**Comment by mars0i** [comment]
Ah, I see.  That makes sense.

**Comment by ryanrhymes** [comment]
you can instead try with `let x = Mat.sequential ~a:1. 1 10;;`

**Comment by mars0i** [comment]
Thanks.  I must have noticed the optional arguments to `sequential` at some point, but completely forgot about them.

**Pull request merged**
