### PR TITLE
start api doc review: owl_maths.mli

### PR DESCRIPTION
**Pull request by nilsbecker**
changes are only in the doc strings of math functions. please check that the markup of math vs. code vs. displayed latex math is ok.  if yes i'll stick to it in future doc edits. 

style choice: one could also s/gives/returns everywhere.

### CODE REVIEW

**Comment by ryanrhymes** [comment]
This looks very good to me. I recommend using `:math:` more often for inline math in restructuredtext, they look really nice. Thank you Nils 💯

**Comment by ryanrhymes** [comment]
Fixed some small things, now the new doc is here: http://www.cl.cam.ac.uk/~lw525/owl/apidoc/owl_maths.html

**Comment by nilsbecker** [comment]
about using `:math:`: i too find math looks nicer in properly formatted rst. i'm only afraid that this fancy formatting may make the formulas completely disappear when using odoc, or make them less readable when displaying the doc strings from merlin using MerlinDocument . are these valid concerns?

**Comment by ryanrhymes** [comment]
I vaguely remember `odoc` has plan to support restructuredtext in future, but I need to double-check it with my colleagues here ...

**Comment by nilsbecker** [comment]
for now, i will wait with further doc updates until a preferred way to format math has crystallized.

**Pull request merged**
