### PR TITLE
Add option to spec for plplot 3D options plus code to use it

### PR DESCRIPTION
**Pull request by mars0i**
This is for issue #57.

I added a bit of text to the doc comments in the mli file.  Not sure if that's more than you want there.

The commit history is kind of odd looking (to me, at least).  Not worth explaining.

### CODE REVIEW

**Comment by mars0i** [comment]
I ran it through the examples in the tutorial. The only files that differed were the ones using random data, but visually they looked OK.  I'll PR the examples file, too.  I'm trying to separate different kinds of additions into different PRs.

**Comment by ryanrhymes** [comment]
Great! Thanks @mars0i . It is an awesome PR and thanks for the contribution. Could you also revise the tutorial https://github.com/ryanrhymes/owl/wiki/Tutorial:-How-to-Plot-in-Owl%3F and contribute a small example there if possible. 👍 

Ideally, it is better not to expose raw Plplot configurations to Owl users in order to maintain a consistent plotting configuration. I will do some minor refactoring to wrap them up. but it is not a big issue at the moment. :)

**Comment by mars0i** [comment]
Sure, I'd be happy to contribute an example.  I want to wait until the interface has stabilized. 

(I'm using Owl for a presentation at a week-long conference that starts a week from now.  The code has been changing pretty quickly--I'm not complaining, but I might need to stop contributing for a couple of weeks and just make use of my fork, which has some additional changes, until after the conference.  We'll see.  Working on Owl can be a nice way to take a break.)

**Comment by ryanrhymes** [comment]
Sure, this is not urgent at all. I would also recommend using your own fork for the presentation. As you mentioned, the master branch is changing quite fast at the moment.

Good luck with your presentation.

**Pull request merged**
